controller_names:
  - fake_cr3_arm_controller
fake_cr3_arm_controller:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
initial:
   panda_arm: home_pose
